# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-10 22:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag1',
        ),
    ]
