# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-10 22:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_delete_tag1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag1',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('on', models.BooleanField(default=False)),
            ],
        ),
    ]
