# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_delete_tag1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='content',
            field=models.CharField(max_length=200000),
        ),
        migrations.AlterField(
            model_name='pages',
            name='content',
            field=models.CharField(max_length=200000),
        ),
    ]
