# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-13 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0007_auto_20161204_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='title_img',
            field=models.CharField(default='', max_length=200),
        ),
    ]
